INSERT INTO TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES(10001, 'in28minutes', 'Get AWS Certified', CURRENT_DATE(), false);

INSERT INTO TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES(10002, 'in28minutes', 'Get Azure Certified', CURRENT_DATE(), false);

INSERT INTO TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES(10003, 'in28minutes', 'Get Java Certified', CURRENT_DATE(), true);